print("Olá, mundo!")
print("Estou aprendendo Python.")
print("Python é uma linguagem poderosa.")
print("Hoje vou estudar programação.")
print("A prática leva à perfeição.")
print("Algoritmos ajudam a resolver problemas.")
print("Programar pode ser divertido.")
print("Estou desenvolvendo minhas habilidades.")
print("Cada linha de código é um aprendizado.")
print("Python possui uma sintaxe simples.")
print("Vou continuar estudando.")
print("Erros fazem parte do aprendizado.")
print("A programação estimula o raciocínio.")
print("Estou criando meu primeiro programa.")
print("Tecnologia está sempre evoluindo.")
print("Conhecimento é construído com prática.")
print("Hoje é um ótimo dia para aprender.")
print("Meu código está ficando melhor.")
print("Vou alcançar meus objetivos.")
print("Nunca vou parar de aprender.")